name: Pipeline de Execução

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run executable
      run: |
        .\DbUpVersionadorSQL.exe
