name: Executar DbUpVersionadorSQL.exe

on:
  push:
    branches: [ master ]

jobs:
  run-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Executar DbUpVersionadorSQL.exe
        run: ./DbUpVersionadorSQL.exe
